# Generated by Django 2.0.1 on 2018-02-05 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0002_auto_20180202_2242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tagged',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.IntegerField()),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scripts.Script')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scripts.Tag')),
            ],
        ),
    ]
