# Generated by Django 2.0.1 on 2018-02-13 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0006_auto_20180208_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='script',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scripts.Script'),
        ),
        migrations.AlterField(
            model_name='tagged',
            name='script',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scripts.Script'),
        ),
    ]
