# Generated by Django 2.0.1 on 2018-02-14 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0008_auto_20180214_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='tags',
            field=models.ManyToManyField(blank=True, to='scripts.Tag'),
        ),
        migrations.AlterField(
            model_name='line',
            name='script',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scripts.Script'),
        ),
    ]
