# Generated by Django 2.0.1 on 2018-02-14 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0009_auto_20180214_0727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='line',
            name='script',
        ),
    ]
