# Generated by Django 2.0.1 on 2018-02-14 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0010_remove_line_script'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='lines',
            field=models.ManyToManyField(blank=True, to='scripts.Line'),
        ),
    ]
