# Generated by Django 2.0.1 on 2018-02-14 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0011_script_lines'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=5000)),
                ('sentnum', models.IntegerField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='line',
            name='text',
            field=models.TextField(max_length=10000),
        ),
    ]
