# Generated by Django 2.0.1 on 2018-02-14 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0012_auto_20180214_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='sentences',
            field=models.ManyToManyField(to='scripts.Sentence'),
        ),
    ]
