# Generated by Django 2.0.1 on 2018-02-18 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0016_auto_20180218_0612'),
    ]

    operations = [
        migrations.CreateModel(
            name='Line_Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='line',
            options={'ordering': ('linenum',)},
        ),
        migrations.AlterModelOptions(
            name='script_line',
            options={},
        ),
        migrations.RemoveField(
            model_name='line',
            name='sentences',
        ),
        migrations.AlterField(
            model_name='script_line',
            name='script',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scripts.Script'),
        ),
        migrations.AddField(
            model_name='line_sentence',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scripts.Line'),
        ),
        migrations.AddField(
            model_name='line_sentence',
            name='sentence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scripts.Sentence'),
        ),
    ]
