# Generated by Django 2.0.1 on 2018-02-18 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0019_auto_20180218_0619'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='sentences',
            field=models.ManyToManyField(blank=True, through='scripts.Line_Sentence', to='scripts.Sentence'),
        ),
        migrations.AlterField(
            model_name='script_line',
            name='script',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scripts.Script'),
        ),
    ]
