# Generated by Django 2.0.1 on 2018-02-26 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0022_auto_20180218_0632'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Script_CommonWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scripts.Script')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scripts.CommonWord')),
            ],
        ),
        migrations.AlterField(
            model_name='script_line',
            name='script',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scripts.Script'),
        ),
    ]
