# Generated by Django 2.0.1 on 2018-02-26 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0024_auto_20180226_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonword',
            name='wfreq',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='commonword',
            name='wid',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='script_commonword',
            name='script',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scripts.Script'),
        ),
        migrations.AlterField(
            model_name='script_line',
            name='script',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scripts.Script'),
        ),
    ]
