# Generated by Django 2.0.1 on 2018-03-02 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0025_auto_20180226_1813'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='scripts/')),
            ],
        ),
        migrations.CreateModel(
            name='Script_File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scripts.File')),
            ],
        ),
        migrations.AlterModelOptions(
            name='sentence',
            options={'ordering': ['sentnum']},
        ),
        migrations.AddField(
            model_name='script',
            name='common_words',
            field=models.ManyToManyField(blank=True, through='scripts.Script_CommonWord', to='scripts.CommonWord'),
        ),
        migrations.AlterField(
            model_name='script_commonword',
            name='script',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scripts.Script'),
        ),
        migrations.AlterField(
            model_name='script_line',
            name='script',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scripts.Script'),
        ),
        migrations.AddField(
            model_name='script_file',
            name='script',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scripts.Script'),
        ),
        migrations.AddField(
            model_name='script',
            name='scriptfiles',
            field=models.ManyToManyField(blank=True, through='scripts.Script_File', to='scripts.File'),
        ),
    ]
