# Generated by Django 2.0.1 on 2018-03-11 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0035_auto_20180311_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence_translation',
            name='translation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translation', to='scripts.Sentence'),
        ),
        migrations.AlterField(
            model_name='script_commonword',
            name='script',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scripts.Script'),
        ),
        migrations.AlterField(
            model_name='script_file',
            name='script',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scripts.Script'),
        ),
        migrations.AlterField(
            model_name='script_line',
            name='script',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scripts.Script'),
        ),
    ]
