# Generated by Django 2.0.1 on 2018-03-11 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0036_auto_20180311_0058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentence',
            name='sentid',
        ),
        migrations.AddField(
            model_name='sentence',
            name='translations',
            field=models.ManyToManyField(blank=True, through='scripts.Sentence_Translation', to='scripts.Sentence'),
        ),
        migrations.AlterField(
            model_name='script_commonword',
            name='script',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scripts.Script'),
        ),
        migrations.AlterField(
            model_name='script_file',
            name='script',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scripts.Script'),
        ),
        migrations.AlterField(
            model_name='script_line',
            name='script',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scripts.Script'),
        ),
    ]
